### ISSUE TITLE
Attempt to reference field of non-structure array

### ISSUE THREAD

**Issue by shomedas** [mws262/MATLAB-GJK-Collision-Detection#1]
I tried to use your GJK code with matlab 2014a, ubuntu 14.04

i got error:

Warning: Struct field assignment overwrites a value with class "double". See MATLAB R14SP2 Release Notes, Assigning
Nonstructure Variables As Structures Displays Warning, for details. 

> In MAIN_example at 40 
> Attempt to reference field of non-structure array.

Error in MAIN_example (line 44)
S1Coords = S1Obj.Vertices;

can you suggest how to fix it?

**Comment by mws262** [comment]
MATLAB changed the way you can change figure properties in 2014b.

To get a graphics object's field:
S1Coords = S1Obj.Vertices; % New -- 2014b +
S1Coords = get(S1Obj,'Vertices'); % Old -- 2014a -

To set a graphics object's field:
S1Obj.Vertices = anotherMatrix; % New -- 2014b +
set(S1Obj,'Vertices',anotherMatrix); % Old -- 2014a -

The key would be to swap all the first type of lines with the second type to make it compatible with older versions of MATLAB.

---

I made a version called MAIN_example_compatible.m. Try running this. I don't have access to MATLAB 2014a, so I can't verify if I've caught all the changes. Please let me know if it works, thanks!

**Comment by shomedas** [comment]
Hi,
    Thanks for your reply. I have a querry. GJK algorithm works only on
convex shapes. Do you take out the convexhull inside your code? Or do you
assume that the shape is convex. I couldnt find any part finding the convex
hull in your code.

Thanks
shome

**Comment by mws262** [comment]
Hey,
I don't know if what I'm saying is mathematically "provable" since I don't have a lot of experience with convex sets, etc. Here is my thought process:

Whenever a point is sampled (in the support function) to build the simplex, it always picks the point on the shape which is furthest in the sampling direction. This is kind of like evaluating part of the convex hull. If there is a concave part of the shape, those vertices are never chosen because another vertex will be further in that direction. 

In that sense, we sample from the convex hull of the shapes when we need to, but we don't pre-evaluate the whole thing. The algorithm would still work if you gave it a bunch of points on the interior of the polyhedra -- it would just ignore those.

-- Matt
