### ISSUE TITLE
How can we calculate the distance between the two convex shapes?

### ISSUE THREAD

**Issue by shomedas** [mws262/MATLAB-GJK-Collision-Detection#2]
The GJK paper (http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=2083&tag=1) finds the distance between two convex hulls. Is there a way to get the distance from your code?

**Comment by mws262** [comment]
Ah, that's probably where the difference lies. I wrote the code quite awhile ago, and I recall using these as references:
http://www.dyn4j.org/2010/04/gjk-gilbert-johnson-keerthi/
http://www.dyn4j.org/2010/04/gjk-distance-closest-points/

I never implemented the second link (regarding closest points and distance) because my application didn't require it. I'm sure that could be added though. I'll look into that.

**Comment by mrslvg** [comment]
Are you still working on the distance/closest points calculation? I am planning to use your code to do that.
